{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gokit-gorilla-restsvc-chart.name" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gokit-gorilla-restsvc-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
        - path: /engines/
          pathType: Exact
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $svcPort }}
{{- end }}


