apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-gokit-gorilla-restsvc
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-gokit-gorilla-restsvc
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80